apiVersion: v1
kind: Pod
metadata:
  labels:
  name: nginx-helloworld
spec:
  containers:
    - name: redis-app
      image: redis:rc-alpine3.12
      volumeMounts:
      - mountPath: "/redis"
        name: www-data
    - image: nginx
      name: nginx-helloworld
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: www-data
  initContainers:
    - name: git-cloner
      image: alpine/git
      args:
        - clone
        - --single-branch
        - --
        - https://github.com/jmutai/hello-world-nginx.git
        - /data
      volumeMounts:
        - mountPath: /data
          name: www-data
  volumes:
    - name: www-data
      emptyDir: {}